type Category implements Node {
  id: UUID!
  name: String!
  slug: String!
  description: String
  posts: [Post!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input CreateCategoryInput {
  name: String!
  description: String
}

input UpdateCategoryInput {
  name: String
  description: String
}

extend type Query {
  categories: [Category!]!
  category(id: UUID): Category
}

extend type Mutation {
  createCategory(input: CreateCategoryInput!): Category! @auth(role: ADMIN)
  updateCategory(id: UUID!, input: UpdateCategoryInput!): Category! @auth(role: ADMIN)
  deleteCategory(id: UUID!): Boolean! @auth(role: ADMIN)
}
